version: '3'
services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    networks:
      - api-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web-vault
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis-app:
    image: redis:6
    container_name: redis-app
    ports:
      - 6379:6379
    networks:
      - api-network
    volumes:
      - redis-db:/data/redis

  api-app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-api
    ports:
      - '3001:3001'
    networks:
      - api-network
    volumes:
      - .:/app

networks:
  api-network:
    name: app_network

volumes:
  postgres-data:
  pgadmin-data:
  redis-db:
